apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wil-playground
spec:
  rules:
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: wil-playground
              port:
                number: 8888
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wil-playground
  name: wil-playground
spec:
  ports:
    - port: 8888
  protocol: TCP
  selector:
    app: wil-playground

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground
  labels:
    name: wil-playground
spec:
  selector:
    matchLabels:
      app: wil-playground
  template:
    metadata:
      labels:
        app: wil-playground
    spec:
      containers:
      - name: wil-playground
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
